services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - netboi

  web-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8501:8501"
    networks:
      - netboi

networks:
  netboi:
    driver: bridge

volumes:
  ollama:
    driver: local